project_id = "xegucorsaiqvaqqqbizt"

[functions.preview-resume]
verify_jwt = false

[functions.generate-resume]
verify_jwt = true

[functions.generate-resume-html]
verify_jwt = false

[functions.generate-pdf]
verify_jwt = true
